### ISSUE TITLE
[REQ]Add $cipher logo

### ISSUE THREAD

**Issue by beaftoken** [CKBFansDAO/xudtlogos#10]
Add $cipher logo to token 0xac3daa0748f24779f7c665dab8d0e6c39510554050ede421f1f88d105c058444

![me4SX2Tq_400x400](https://github.com/user-attachments/assets/bcece4d8-3590-45ef-98c8-aae8cb1c4759)

**Comment by beaftoken** [comment]
@yixyxiu

**Comment by yixyxiu** [comment]
$CIPHER's logo already exists and is consistent with the logo on [ckb.fi](https://ckb.fi/detail/2/0)

https://xudtlogos.cc/logo/cipher-logo.png
