### ISSUE TITLE
[REQ] Add iCKB xUDT

### ISSUE THREAD

**Issue by phroi** [CKBFansDAO/xudtlogos#11]
Hello folks at CKBFansDAO, iCKB here :wave:
After passing both [internal and external audit](https://github.com/ickb/v1-core/tree/master/scripts#audit), iCKB scripts have been deployed on Testnet and Mainnet. Under the [proposal's deployment section](https://github.com/ickb/proposal#non-upgradable-deployment) you can find all the metadata. Also the [png logo is available in the repo](https://github.com/ickb/proposal/blob/master/logo.png).

Please, could you add iCKB xUDT metadata on CKBFansDAO?

Additionally, I'd like to add a couple of info:
- The official website is ickb.org
- The official telegram is https://t.me/NervosNation/307406 (A dedicated thread on Nervos Nation)

Keep up the Great Work :muscle:
Phroi

**Comment by yixyxiu** [comment]
The iCKB xUDT metadata added, and looks good:

![image](https://github.com/user-attachments/assets/67174082-8f75-448c-8fe8-810e32d5f0db)

[Take a look](https://xudtlogos.cc/)

**Comment by phroi** [comment]
Nice job, thank you a lot!! :pray:
