### ISSUE TITLE
[REQ]Add Nervos Network - CKB logo 

### ISSUE THREAD

**Issue by YouthSake** [CKBFansDAO/xudtlogos#12]
Logo for $BitCat, address: 0x9320a9f1a9bff385ed53449b5284b8d961c731945ad47ab270f3cb82c0795c19

![img_v3_02fh_2b509c3d-5b8b-47d1-b09a-2f6d5f922ehu](https://github.com/user-attachments/assets/f962e899-3d87-48b4-ba89-3edd5fcc7412)

**Comment by yixyxiu** [comment]
Looks good:

![image](https://github.com/user-attachments/assets/4a13774a-3aa3-480e-b859-35252c55095c)
