### ISSUE TITLE
[REQ]Add $Girl logo 

### ISSUE THREAD

**Issue by lilili889** [CKBFansDAO/xudtlogos#2]
![WechatIMG2871](https://github.com/user-attachments/assets/8062ab56-f1df-45a7-8294-e9c1b8548a2a)

**Comment by yixyxiu** [comment]
added

**Comment by yixyxiu** [comment]
![image](https://github.com/user-attachments/assets/b5bb8021-fb20-437d-b1ca-af42349c2208)
