### ISSUE TITLE
[REQ]Add $CANDY logo 

### ISSUE THREAD

**Issue by Neonckb** [CKBFansDAO/xudtlogos#3]
![CANDYYRGBPP](https://github.com/user-attachments/assets/9f2bd78d-98a2-4ad4-9b1f-16a99e2dcc1a)

**Comment by Neonckb** [comment]
Also add X:
https://x.com/candy_rgbpp

**Comment by yixyxiu** [comment]
Please provide the URL for $CANDY from explorer.nervos.org, which should be something like: https://explorer.nervos.org/xudt/{your token type_hash}

**Comment by Neonckb** [comment]
> Please provide the URL for $CANDY from explorer.nervos.org, which should be something like: [https://explorer.nervos.org/xudt/{your](https://explorer.nervos.org/xudt/%7Byour) token type_hash}

https://explorer.nervos.org/xudt/0x667776d1ea35d9e446c957f0394741303e40f8aada7f14eb8e1f33c707fcddfd

**Comment by yixyxiu** [comment]
![image](https://github.com/user-attachments/assets/b01ba2fa-cd76-4bfc-b34f-7010c12e6f32)
https://utxoswap.xyz/swap/0x667776d1ea35d9e446c957f0394741303e40f8aada7f14eb8e1f33c707fcddfd/CKB

**Done.**
