### ISSUE TITLE
[REQ]Add Nervos Network - Beaf Logo

### ISSUE THREAD

**Issue by beaftoken** [CKBFansDAO/xudtlogos#4]
Hi team

Submitting the logo for the BEAF token. Please find the attached file for your review and approval.

Thank you for your attention to this matter. We look forward to your feedback.

![Artwork 300 PPI-01](https://github.com/user-attachments/assets/f6abaaf1-960b-443f-9635-52c61d68ec56)
![Artwork 150 PPI-01](https://github.com/user-attachments/assets/5f01ac84-5854-41c4-9dba-9f3545321a1e)
![Artwork 72 PPI-01](https://github.com/user-attachments/assets/d63cc7db-28fa-4efb-bccd-756f27250023)

**Comment by beaftoken** [comment]
token policy:
0xfbd235ba8e5b1f8f7df6bd51e8756d52c05ef358d30e7bcfee8a73b6a9c185c9

Also add X account:
https://x.com/beaftoken

Also add website:
https://www.beaftoken.com/

**Comment by yixyxiu** [comment]
Your provided logo dimensions are not 1:1, which may cause stretching and distortion when displayed. Please double-check the dimensions again.

**Comment by yixyxiu** [comment]
fixed: https://xudtlogos.cc/logos/beaf-logo.png
