### ISSUE TITLE
[REQ]Add $RGB++ logo

### ISSUE THREAD

**Issue by Dongtu345** [CKBFansDAO/xudtlogos#5]
#RGB++ Protocol Coin
社区网址:https://rgbpp.vip
官推:@rgbppcoin
RRB++ COIN合约地址:0xb5fdb4e8ad52f5e3ed4a294c01ca99f7811b06baef2e7fce5b7d4ebbf006717d

Coin Logo:

![rgb++-logo](https://github.com/user-attachments/assets/743b5943-8528-4c7c-94d9-15eb2ef21658)

**Comment by yixyxiu** [comment]
Done: https://xudtlogos.cc/logos/rgb++-logo.png
