### ISSUE TITLE
[REQ]Add Nervos Network - CKB logo 

### ISSUE THREAD

**Issue by rgbcat-io** [CKBFansDAO/xudtlogos#7]
Xudt Type Hash :0xd3398f476413dde2653b13f08debe9983d5746b4303e9108f79648711608ccb0
Trade Url：https://utxoswap.xyz/swap/CKB/0xd3398f476413dde2653b13f08debe9983d5746b4303e9108f79648711608ccb0
X: @rgbcat_io

![icon](https://github.com/user-attachments/assets/79148d85-87eb-4cee-b341-97c545d70304)

**Comment by yixyxiu** [comment]
done

![image](https://github.com/user-attachments/assets/6b4c9847-a60b-4115-af82-4bc53559fa28)

![image](https://github.com/user-attachments/assets/6e0dcf3d-df38-4233-9f98-fa62f4397599)
